### ISSUE TITLE
Warning: bind(): React component methods may only be bound to the component instance

### ISSUE THREAD

**Issue by kimmobrunfeldt** [alex3165/react-mapbox-gl#75]
I'm using react-mapbox-gl@0.18.0, react@^15.4.1, react-dom@^15.4.1 versions.

When adding a ZoomControl which has an `onControlClick` callback, React gives an error:

![screenshot 2016-12-07 18 50 32](https://cloud.githubusercontent.com/assets/1232405/20977371/0d306136-bcae-11e6-9153-84d8ec7b38c1.png)

The error is coming from this line: https://github.com/alex3165/react-mapbox-gl/blob/1bd531359d89f3c5d4eb97285c380b68e6761ebf/src/zoom-control.js#L103 where the component calls .bind for the parent component's (MyMap) method.

**MyMap.js:**

```js
import React from 'react';
import ReactMapboxGl, { Layer, Feature, Marker, ZoomControl } from 'react-mapbox-gl';

const MyMap = React.createClass({
  getInitialState() {
    return {
      mapCenter: [0, 0],
      zoom: 2,
      style: 'mapbox://styles/mapbox/light-v9',
    };
  },

  render() {
    const { state, props } = this;

    return (
      <div className="MyMap" style={{width: 500, height: 700}}>
          <ReactMapboxGl
            center={state.mapCenter}
            zoom={[state.zoom]}
            style={state.style}
            accessToken="pk.eyJ1IjoiZmFicmljOCIsImEiOiJjaWc5aTV1ZzUwMDJwdzJrb2w0dXRmc2d0In0.p6GGlfyV-WksaDV_KdN27A"
          >
            <ZoomControl
              zoomDiff={1}
              onControlClick={this._onControlClick}
            />
          </ReactMapboxGl>
      </div>
    );
  },

  _onControlClick(map, zoomDiff) {
    const zoom = map.getZoom() + zoomDiff;
    this.setState(() => ({ zoom: zoom }));
  }
});

export default MyMap;

```

**Comment by alex3165** [comment]
Can you try to modify your `MyMap.js` to :
```
            <ZoomControl
              zoomDiff={1}
              onControlClick={this._onControlClick.bind(this)}
            />
```

**Comment by kimmobrunfeldt** [comment]
That doesn't help. It just adds a new warning:

```
Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See AlvarMap
```

The warning comes because ZoomControl component is messing with MyMap component's method.

**zoom-control.js, row 103:**
```
onClick={onControlClick.bind(this, map, zoomDiff)}> 
```

There the `onControlClick` method is MyMap's method: `MyMap._onControlClick`. React warns because you shouldn't be rebinding the `this` to a new component.

**Comment by alex3165** [comment]
I have published a patch (`0.19.1`) where I have replaced the bind with an arrow function, let me know if it fix your issue.

**Comment by kimmobrunfeldt** [comment]
I tested with version 0.19.1 but the problem still persists.

**Comment by alex3165** [comment]
Can you send me a link to your project ? or a link to a jsfiddle ?

**Comment by philpl** [comment]
The affected line was changed in a previous patch and we don't have an example available, to reproduce the issue, thus I need to close this for now 😄

**Comment by kimmobrunfeldt** [comment]
Sorry for taking so long. I don't know how I tested it before but I can now confirm that bump from 0.18.0 -> 0.19.1 fixed this issue.

A reproducible example of the bug: https://github.com/kimmobrunfeldt/react-mapbox-gl-bug/blob/master/src/MyMap.js
